### ISSUE TITLE
refactored for API V2 still not working

### ISSUE THREAD

**Issue by nnworkspace** [watson-developer-cloud/assistant-intermediate#7]
Hi,

I cloned the latest repository and tried out the app. It always started with HTTP code 500 (internal server error). As I looked into the app.js, line 58 to 61 caught my eyes:

```javascript

private: {
          function_creds: {
            user: process.env.CLOUD_FUNCTION_USER,
            password: process.env.CLOUD_FUNCTION_PASS,
          },
```

What are these values? In the readme.md, there is no instruction about how to set these values in the .env file. 

What if we do not want to use cloud Foundry and just want to test it locally and then pack it into a docker image? We can write the docker file ourselves, but what are these env values? Can we just remove these lines from the app.js?

Another issue is, we cannot import the json data into our watson assistant service. This file is too big for the Lite account. But we are happy enough if we can get the 500 error away....we can author the dialogs ourselves on the bluemix GUI..... 

Thank you!

Regards,
Ning

**Comment by mitchmason** [comment]
Those are not cloud foundry, they are cloud functions. They are for sending your cloud function credentials privately to make external callouts from dialog nodes. When sent into the private object they are not passed back and forth in context so cannot be sniffed in network tools etc.

**Comment by mitchmason** [comment]
this app looks like it pulls in the sdk and then grabs your Watson assistant credentials through that.

**Comment by germanattanasio** [comment]
@stevenpkg can you look ☝️

**Comment by stevenpkg** [comment]
Those credentials are not required now, simple change to:

```code
private: {
    function_creds: {
      user: '' ,
      password: '',
    },
  },
```

I will be remove that code soon
